PackageIdentifier: AndinWin.AndinWin
PackageVersion: 0.1.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.22000.0
Architecture: x64
InstallerType: inno
Scope: user
UpgradeBehavior: install
FileExtensions:
- apk
AppsAndFeaturesEntries:
- DisplayName: AndinWin
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/aicommands79-debug/andinwin/releases/download/v0.1.2/AndinWin-Setup-0.1.2.exe
  InstallerSha256: FFBAEAA4A9C64A1F2B2831DFDEAC7D2198663B9381491DC5691AB637CDBCAD23
  InstallerSwitches:
    Silent: /SILENT
    SilentWithProgress: /SILENT
ManifestType: installer
ManifestVersion: 1.6.0
